import {useRef,useState,type FormEvent} from 'react';
import {useMutation,useQuery} from 'convex/react';
import {anyApi} from 'convex/server';
import {ConvexError} from 'convex/values';
type Customer={_id:string;name:string;publicId:string};
type Wallet={_id:string;walletId:string;balanceMicros:number;heldMicros:number;spentMicros:number};
type Entry={_id:string;walletId:string;amountMicros:number;balanceAfter:number;heldAfter:number;note:string;createdAt:number};
type Command={key:string;amountMicros:number;note:string};
const usd=(n:number)=>`$${(n/1_000_000).toFixed(4)}`;
function load(id:string):Command|null{try{const c=JSON.parse(sessionStorage.getItem('mashhad-ai-'+id)??'null');return c&&typeof c.key==='string'&&Number.isSafeInteger(c.amountMicros)&&typeof c.note==='string'?c:null}catch{return null}}
export function AiWalletAdmin({customers}:{customers:Customer[]}){
 const data=useQuery(anyApi.wallets.aiAdmin) as {wallets:Wallet[];ledger:Entry[]}|undefined;
 const [selected,setSelected]=useState(''),[search,setSearch]=useState('');
 if(!data)return <section className="panel">جارٍ تحميل محافظ المناقشة…</section>;
 const customer=customers.find(c=>c._id===selected);
 return <><section className="panel"><h2>رصيد الذكاء الاصطناعي للمناقشة والتخطيط</h2><p>محفظة واحدة لكل زبون بالدولار، مستقلة عن نقاط إنتاج الفيديو. شحنها لا يشحن حساب المزود. لا يوجد حد صرف لكل فيلم؛ المتابعة تعتمد على الرصيد المتاح.</p><div className="search"><input aria-label="البحث عن محفظة المناقشة" value={search} onChange={e=>setSearch(e.target.value)} placeholder="الاسم أو معرّف الزبون"/></div><div className="account-grid">{customers.filter(c=>(c.name+' '+c.publicId).toLowerCase().includes(search.toLowerCase())).map(c=>{const w=data.wallets.find(w=>w.walletId===c._id);return <button className="account" key={c._id} onClick={()=>setSelected(c._id)}><h3>{c.name}</h3><code>{c.publicId}</code><div className="balance" dir="ltr">{usd((w?.balanceMicros??0)-(w?.heldMicros??0))}</div><small>متاح للمناقشة · محجوز <span dir="ltr">{usd(w?.heldMicros??0)}</span></small></button>})}</div>{!customers.length&&<p>أنشئ الزبون معرّف محفظته من مشهد أولًا.</p>}</section>{customer&&<AiEditor key={customer._id} customer={customer} wallet={data.wallets.find(w=>w.walletId===customer._id)}/>}<section className="panel"><h2>آخر 100 حركة للذكاء الاصطناعي</h2><div className="ledger">{data.ledger.map(e=><article key={e._id}><div><strong>{customers.find(c=>c._id===data.wallets.find(w=>w._id===e.walletId)?.walletId)?.name??'زبون'}</strong><p>{e.note}</p><small dir="ltr">{new Date(e.createdAt).toLocaleString('en-GB')}</small></div><div className="ledger-number"><b dir="ltr">{usd(e.amountMicros)}</b><small>الرصيد <span dir="ltr">{usd(e.balanceAfter)}</span> · محجوز <span dir="ltr">{usd(e.heldAfter)}</span></small></div></article>)}</div></section></>;
}
function AiEditor({customer:c,wallet:w}:{customer:Customer;wallet?:Wallet}){
 const adjust=useMutation(anyApi.wallets.adjustAi),[amount,setAmount]=useState('1'),[note,setNote]=useState(''),[debit,setDebit]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[pending,setPending]=useState<Command|null>(()=>load(c._id)),lock=useRef(false);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current)return;const value=Number(amount),micros=Math.round(value*1_000_000);if(!pending&&(!Number.isFinite(value)||value<=0||micros<1||micros>1_000_000_000||!note.trim()||Math.abs(value*1_000_000-micros)>.00001)){setMessage('أدخل مبلغًا موجبًا حتى 1000 دولار وبحد 6 خانات عشرية وسبب الحركة.');return;}
 const command=pending??{key:crypto.randomUUID(),amountMicros:micros*(debit?-1:1),note:note.trim()};lock.current=true;setBusy(true);
 try{sessionStorage.setItem('mashhad-ai-'+c._id,JSON.stringify(command));setPending(command);await adjust({walletId:c._id,...command});sessionStorage.removeItem('mashhad-ai-'+c._id);setPending(null);setNote('');setMessage('تم تحديث رصيد المناقشة وتسجيل الحركة مرة واحدة.');}catch(e){if(e instanceof ConvexError){sessionStorage.removeItem('mashhad-ai-'+c._id);setPending(null);}setMessage(e instanceof Error?e.message:'تعذر الاتصال؛ إعادة المحاولة تستخدم نفس الحركة.');}finally{lock.current=false;setBusy(false);}
 }
 return <section className="panel"><h2>رصيد مناقشة {c.name}</h2><code>{c.publicId}</code><p>المتاح <b dir="ltr">{usd((w?.balanceMicros??0)-(w?.heldMicros??0))}</b> · الاستخدام المسجل <b dir="ltr">{usd(w?.spentMicros??0)}</b></p><form onSubmit={submit}><label>الحركة<select disabled={busy||!!pending} value={debit?'debit':'credit'} onChange={e=>setDebit(e.target.value==='debit')}><option value="credit">شحن رصيد المناقشة</option><option value="debit">تصحيح بخصم إداري</option></select></label><label>المبلغ بالدولار<input type="number" dir="ltr" step="0.000001" min="0.000001" max="1000" required disabled={busy||!!pending} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>سبب الحركة<input required maxLength={500} disabled={busy||!!pending} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy}>{busy?'جارٍ الحفظ…':pending?'إعادة إرسال نفس الحركة':'تسجيل حركة الرصيد'}</button></form>{message&&<p className="notice" role="status">{message}</p>}</section>;
}
